[package]
name = "retype"
version = "0.3.0"
authors = ["Alexander Mescheryakov <freecoder.xx@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.11"
syn = { version = "0.15.26", features = ["full", "extra-traits"] }
toml = "0.4.10"
lazy_static = "1.2.0"